import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CategoryCard from '../components/CategoryCard'
import {useState} from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home({ productsFiltered }) {

  console.log(productsFiltered);
  console.log('index.js | productsFiltered');
  {
    productsFiltered.map((product) => (
      console.log('BEGIN index.js product'),
      console.log(product),
      console.log('END index.js product'),
      console.log('Begin product.imageUrl'),
      console.log(product.imageUrl),
      console.log('END product.imageUrl')
    ))
  }

  return (
    <div>
      <Head>
        <title>Next React Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className={styles.small}>
          {/* <ProductsList productsFiltered={productsFiltered} ></ProductsList> */}
          <CategoryCard imageUrl={productsFiltered[0].imageUrl} name={productsFiltered[0].name} />
          <CategoryCard imageUrl={productsFiltered[1].imageUrl} name={productsFiltered[1].name} />
          <CategoryCard imageUrl={productsFiltered[2].imageUrl} name={productsFiltered[2].name} />
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {

  const responseProducts = await fetch('https://60a2b8707c6e8b0017e26016.mockapi.io/products')

  const productsFiltered = await responseProducts.json()

  return {
    props: {
      productsFiltered
    },
  };
};
